import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import auth from './routes/auth.js';
import orgs from './routes/organizations.js';
import projects from './routes/projects.js';
import tasks from './routes/tasks.js';
import { errorHandler } from './lib/http.js';

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_ORIGIN, credentials: true }));
app.use(express.json({ limit: '100kb' }));
app.use(cookieParser());
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/auth', auth);
app.use('/api/organizations', orgs);
app.use('/api/projects', projects);
app.use('/api/tasks', tasks);
app.use((req, res) => res.status(404).json({ error: 'Not found' }));
app.use(errorHandler);
export default app;
